micronaut:
  application:
    name: aluguel-carros-api
  server:
    port: 8080
    context-path: /api
  security:
    enabled: true
    authentication: bearer
    intercept-url-map:
      - pattern: /auth/**
        access:
          - isAnonymous()
      - pattern: /login
        access:
          - isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_SECRET:AluguelCarros_SecretKey_AtLeast256Bits_1234567890ABCDEF}"

jackson:
  serialization:
    writeDatesAsTimestamps: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/aluguel_carros
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    db-type: postgres

jpa:
  default:
    entity-scan:
      packages:
        - com.aluguelcarros.model
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
